### ISSUE TITLE
feat: take a look of fast-json-stringify

### ISSUE THREAD

**Issue by cesco69** [andrehrferreira/cmmv-server#2]
One of the reason because fastify is faster than express is that use [fast-json-stringify](https://www.npmjs.com/package/fast-json-stringify) instead of JSON.stringify (https://github.com/andrehrferreira/cmmv-server/blob/main/packages/server/lib/response.ts#L1251)

There is also a middleware for express https://www.npmjs.com/package/express-fast-json-stringify

Side note: you're doing a great job!

**Comment by andrehrferreira** [comment]
I took a look at this fast-json-stringify, but I haven't stopped to implement it yet because it uses schema to optimize the JSON parser, but I'll look further ahead at everything possible to optimize the project while maintaining compatibility with Express.

**Comment by andrehrferreira** [comment]
function included in the main project
